name: Run bot

on:
  schedule:
    - cron: "50 * * * *"
  push:
    branches:
    - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16'
        cache: 'yarn'

    - name: Install dependencies
      run: yarn

    - name: Start bot
      env:
        BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
        ETHERSCAN_TOKEN: ${{ secrets.ETHERSCAN_TOKEN }}
        INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
        FTMSCAN_TOKEN: ${{ secrets.FTMSCAN_TOKEN }}
      run: yarn start
